/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites. */
function initHands() {
	setup.clothes.hands = [
		{
			index: 0,
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			integrity: 0,
			integrity_max: 0,
			fabric_strength: 0,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},

		{
			index: 1,
			name: "fingerless gloves",
			name_cap: "Fingerless gloves",
			variable: "fingerlessgloves",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 5,
			cost: 1000,
			description: "Fingerless gloves to keep your hands warm.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "fingerless_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 2,
			name: "mittens",
			name_cap: "Mittens",
			variable: "mittens",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 50,
			cost: 400,
			description: "Isn't shaped for individual fingers, but that shouldn't be a problem.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "mittens.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 3,
			name: "arm warmers",
			name_cap: "Arm warmers",
			variable: "armwarmers",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 40,
			cost: 1000,
			description: "Keep your arms warm.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "arm_warmers.png",
			accIcon: "arm_warmers_acc.png",
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 4,
			name: "lace arm warmers",
			name_cap: "Lace arm warmers",
			variable: "lacewarmers",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 15,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			warmth: 5,
			cost: 2500,
			description: "Fashionable.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lace_arm_warmers.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 5,
			name: "long leather gloves",
			name_cap: "Long leather gloves",
			variable: "longleathergloves",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal", "sticky_fingers", "stealthy"],
			gender: "n",
			warmth: 10,
			cost: 8000,
			description: "Fashionable and ready to slip into pockets.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "long_leather_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 6,
			name: "pom poms",
			name_cap: "Pom poms",
			variable: "pompoms",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "athletic"],
			gender: "f",
			femininity: 200,
			warmth: 15,
			cost: 1500,
			description: "For cheering your team to victory.",
			shop: ["clothing", "school", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "pom_poms.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 7,
			name: "gold bracelets",
			name_cap: "Gold bracelets",
			variable: "gold",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["costume", "serving"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 25000,
			description: "Eye-catching and exotic.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "gold_bracelets.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 8,
			name: "cow sleeves",
			name_cap: "Cow sleeves",
			variable: "cow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["costume"],
			gender: "n",
			warmth: 20,
			cost: 1000,
			description: "Cute cow print.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cow_sleeves.png",
			accIcon: "",
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},

		{
			index: 9,
			name: "work gloves",
			name_cap: "Work gloves",
			variable: "workgloves",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "n",
			warmth: 50,
			cost: 1500,
			description: "For getting your hands dirty.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "work_gloves.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1,
		},
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.hands = [
		{
			index: 0,
			name: "ann_tutu",
			name_cap: "ann_tutu", cn_name_cap: "兔兔气球",
			variable: "ann_tutu",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			warmth: 10,
			cost: 5000,
			description: "一个十分可爱的气球，上面是一个小兔子图案，看起来能让人内心感到温暖。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "ann_tutu.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 0
		},
	
		{
			index: 1,
			name: "ann_sickle",
			name_cap: "ann_sickle", cn_name_cap: "镰刀归无",
			variable: "ann_sickle",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "stealthy"],
			gender: "n",
			warmth: 10,
			cost: 40400,
			description: "“所有这些疯狂皆源于我们自己。”",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "ann_sickle.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 0
		},
	
		{
			index: 12,
			name: "hiWhitney",
			name_cap: "hiWhitney", cn_name_cap: "画着惠特尼的纸",
			variable: "hiWhitney",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 10,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["bellyHide", "serving"],
			gender: "f",
			warmth: 10,
			cost: 30000,
			description: "惠特尼问你为什么要随身带着那个蠢到爆的画——你说记录美好时刻。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "hiWhitney.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1
		},
	
		{
			index: 1,
			name: "small hand light",
			name_cap: "small hand light", cn_name_cap: "小号手提灯",
			variable: "smallhandlight",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 200,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "unstealthy"],
			gender: "n",
			warmth: 20,
			cost: 1000,
			description: "玻璃罩内的光芒静静地闪烁，在黑暗中十分显眼。",
			shop: ["clothing", "forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "smallhandlight.png",
			accIcon: "smallhandlight_acc.png",
			mainImage: 0,
			leftImage: 0,
			rightImage: 1
		},
	
		{
			index: 0,
			name: "shugo chara",
			name_cap: "shugo chara", cn_name_cap: "守护蛋",
			variable: "shugo chara",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			warmth: 10,
			cost: 5000,
			description: "每个女孩都拥有的守护蛋。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "shugochara.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 0
		},
	
		{
			index: 12,
			name: "tianshishoust",
			name_cap: "tianshishoust", cn_name_cap: "天女兽配饰",
			variable: "tianshishoust",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 10,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["bellyHide", "serving"],
			gender: "f",
			warmth: 10,
			cost: 30000,
			description: "炫酷。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "tianshishoust.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 5,
			name: "lxzst",
			name_cap: "lxzst", cn_name_cap: "旅行者手套",
			variable: "lxzst",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["athletic", "normal"],
			gender: "n",
			warmth: 10,
			cost: 8000,
			description: "异世界的护腕。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lxzst.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 1,
			name: "colored lantern bracelet",
			name_cap: "Colored lantern bracelet", cn_name_cap: "彩灯手链",
			variable: "colored lantern bracelet",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 50,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 15,
			cost: 1500,
			description: "用一串彩灯做成的手链，甚至可以接电。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "colored_lantern_bracelet.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 0,
			rightImage: 1
		},
	
		{
			index: 5,
			name: "luotyst",
			name_cap: "luotyst", cn_name_cap: "洛天依手套",
			variable: "luotyst",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["athletic", "normal"],
			gender: "n",
			warmth: 10,
			cost: 8000,
			description: "用来cos洛天依。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "luotyst.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 5,
			name: "heishast",
			name_cap: "heishast", cn_name_cap: "黑纱手套",
			variable: "heishast",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["athletic", "normal"],
			gender: "n",
			warmth: 10,
			cost: 8000,
			description: "简约又好看。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "heishast.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 5,
			name: "tegong shoutao",
			name_cap: "tegong shoutao", cn_name_cap: "特工的手套",
			variable: "tegong shoutao",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal", "sticky_fingers", "stealthy"],
			gender: "n",
			warmth: 10,
			cost: 8000,
			description: "超人气小说《特工狂妃把夫宠》【穿越】【大女主】【甜宠】【智斗】【gb】  翻页开始阅读→。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "tegong shoutao.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 1,
			name: "madoka gloves",
			name_cap: "madoka", cn_name_cap: "鹿目圆香的手套",
			variable: "madokagloves",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["normal"],
			gender: "n",
			warmth: 20,
			cost: 400,
			description: "art by Kosyuku",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "madoka_feet.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 1,
			name: "yebdst",
			name_cap: "yebdst", cn_name_cap: "雅儿贝德手套",
			variable: "yebdst",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			type: ["normal"],
			gender: "n",
			warmth: 20,
			cost: 400,
			description: "世界没有正确答案，只能继续向前，即便脚底满是后悔与苦恼带来的伤痕，也要继续前进。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "yebdst.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 1,
			name: "zhiyechangzhang",
			name_cap: "Zhiyechangzhang", cn_name_cap: "织夜长杖",
			variable: "zhiyechangzhang",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["mask", "sticky_fingers", "stealthy", "sleep"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "纺起午夜的丝线。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "zhiyechangzhang.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 21,
			name: "verosika",
			name_cap: "verosika", cn_name_cap: "绑带手套",
			variable: "verosika",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 15,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "f",
			warmth: 5,
			cost: 2500,
			description: "维罗茜卡的手套。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "verosika shoutao.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 1
		},
	
		{
			index: 5,
			name: "fgwl",
			name_cap: "Fgwl",
			cn_name_cap: "三脚架",
			variable: "fgwl",
			integrity_max: 200,
			integrity: 200,
			fabric_strength: 50,
			reveal: 50,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["formal", "athletic"],
			gender: "n",
			femininity: 0,
			warmth: 1,
			cost: 1000,
			description: "三脚架",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			back_img_colour: 0,
			cursed: 0,
			location: 0,
			iconFile: "sanjiaojj.png",
			accIcon: 0,
			mainImage: 0,
			leftImage: 1,
			rightImage: 0,
		},
	];

	setup.moddedClothes.hands.forEach((x, i) => (x.index = setup.clothes.hands.length + i));
	setup.clothes.hands.push(...setup.moddedClothes.hands);
}
window.initHands = initHands;
