/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites. */
function initFace() {
	setup.clothes.face = [
		{
			index: 0,
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},
		{
			index: 1,
			name: "glasses",
			name_cap: "Glasses",
			variable: "glasses",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "light blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Makes studying easier, but you might be picked on at school.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "glasses.png",
			accIcon: 0,
		},
		{
			index: 2,
			name: "cool shades",
			name_cap: "Cool shades",
			variable: "coolshades",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Makes status rise faster at school.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cool_shades.png",
			accIcon: 0,
		},
		{
			index: 3,
			name: "surgical mask",
			name_cap: "Surgical mask",
			variable: "surgicalmask",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["mask", "covered"],
			gender: "n",
			warmth: 10,
			cost: 2000,
			description: "Hides your identity.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "surgical_mask.png",
			accIcon: 0,
		},
		{
			index: 4,
			name: "gag",
			name_cap: "Gag",
			variable: "gag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "Keeps your mouth shut.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 5,
			name: "blindfold",
			name_cap: "Blindfold",
			variable: "blindfold",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "blindfold"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "Keeps you in the dark.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 6,
			name: "gag and blindfold",
			name_cap: "Gag and blindfold",
			variable: "gagblindfold",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1000,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag", "blindfold"],
			gender: "n",
			warmth: 0,
			cost: 3000,
			description: "Keeps your mouth shut and eyes covered.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 7,
			name: "skulduggery mask",
			name_cap: "Skulduggery mask",
			variable: "skulmask",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy"],
			gender: "n",
			warmth: 0,
			cost: 23000,
			description: "For those up to no good.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "skulduggery_mask.png",
			accIcon: 0,
		},
		{
			index: 8,
			name: "low frame glasses",
			name_cap: "Low frame glasses",
			variable: "lowframe",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Makes studying easier, but you might be picked on at school.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "low_frame_glasses.png",
			accIcon: 0,
		},
		{
			index: 9,
			name: "half moon glasses",
			name_cap: "Half moon glasses",
			variable: "halfmoon",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Makes studying easier, but you might be picked on at school.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "half_moon_glasses.png",
			accIcon: 0,
		},
		{
			index: 10,
			name: "deep frame glasses",
			name_cap: "Deep frame glasses",
			variable: "deepframe",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Makes studying easier, but you might be picked on at school.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "deep_frame_glasses.png",
			accIcon: 0,
		},
		{
			index: 11,
			name: "square shades",
			name_cap: "Square shades",
			variable: "square",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Makes status rise faster at school.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "square_shades.png",
			accIcon: 0,
		},
		{
			index: 12,
			name: "round shades",
			name_cap: "Round shades",
			variable: "round",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Makes status rise faster at school.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "round_shades.png",
			accIcon: 0,
		},
		{
			index: 13,
			name: "shield shades",
			name_cap: "Shield shades",
			variable: "shield",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Makes status rise faster at school.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "shield_shades.png",
			accIcon: 0,
		},
		{
			index: 14,
			name: "cat eye shades",
			name_cap: "Cat eye shades",
			variable: "cateye",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Makes status rise faster at school.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cat_eye_shades.png",
			accIcon: 0,
		},
		{
			index: 15,
			name: "aviators",
			name_cap: "Aviators",
			variable: "aviator",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["grey", "steel", "blue steel", "bronze", "gold", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Makes status rise faster at school.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "aviators.png",
			accIcon: 0,
		},
		{
			index: 16,
			name: "punk shades",
			name_cap: "Punk shades",
			variable: "punk",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 3500,
			description: "Makes status rise faster at school.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "punk_shades.png",
			accIcon: 0,
		},
		{
			index: 17,
			name: "muzzle",
			name_cap: "Muzzle",
			variable: "muzzle",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["gag"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "Keeps your dangerous mouth shut.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 18,
			name: "mummy facewrap",
			name_cap: "Mummy facewrap",
			variable: "mummy",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 1,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["costume"],
			gender: "n",
			warmth: 10,
			cost: 500,
			description: "Feels like it's made from toilet paper.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "mummy_facewrap.png",
			accIcon: 0,
		},
		{
			index: 19,
			name: "swimming goggles",
			name_cap: "Swimming goggles",
			variable: "swimgoggles",
			integrity: 70,
			integrity_max: 70,
			fabric_strength: 25,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["swim", "diving"],
			gender: "n",
			warmth: 10,
			cost: 1500,
			description: "For keeping your vision clear down below.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "swimming_goggles.png",
			accIcon: 0,
		},
		{
			index: 20,
			name: "belly dancer's veil",
			name_cap: "Belly dancer's veil",
			variable: "belly",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["dance"],
			gender: "n",
			warmth: 10,
			cost: 8000,
			description: "Exotic and enticing.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "belly_dancers_veil.png",
			accIcon: "belly_dancers_veil_acc.png",
		},
		{
			index: 21,
			name: "muzzle",
			name_cap: "Muzzle",
			variable: "muzzlefetish",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["grey", "black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["gag", "fetish", "covered"],
			gender: "n",
			warmth: 0,
			cost: 12000,
			description: "Keeps your dangerous mouth shut.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "muzzle.png",
			accIcon: 0,
		},
		{
			index: 22,
			name: "gag",
			name_cap: "Gag",
			variable: "gagfetish",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "Keeps your mouth shut.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "gag.png",
			accIcon: 0,
		},
		{
			index: 23,
			name: "bit gag",
			name_cap: "Bit gag",
			variable: "bitgag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "Keeps your mouth shut.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "bit_gag.png",
			accIcon: 0,
		},
		{
			index: 24,
			name: "wolf muzzle",
			name_cap: "Wolf muzzle",
			variable: "wolfmuzzle",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "Keeps your mouth shut.",
			shop: [],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "wolf_muzzle.png",
			accIcon: 0,
		},
		{
			index: 25,
			name: "kitty muzzle",
			name_cap: "Kitty muzzle",
			variable: "kittymuzzle",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "Keeps your mouth shut.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "kitty_muzzle.png",
			accIcon: 0,
		},
		{
			index: 26,
			name: "cloth gag",
			name_cap: "Cloth gag",
			variable: "clothgag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "Keeps your mouth shut.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cloth_gag.png",
			accIcon: 0,
		},
		{
			index: 27,
			name: "panty gag",
			name_cap: "Panty gag",
			variable: "pantygag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "Keeps your mouth shut.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "panty_gag.png",
			accIcon: 0,
		},
		{
			index: 28,
			name: "tape gag",
			name_cap: "Tape gag",
			variable: "tapegag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "Keeps your mouth shut.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "tape_gag.png",
			accIcon: 0,
		},
		{
			index: 29,
			name: "penis gag",
			name_cap: "Penis gag",
			variable: "penisgag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 4500,
			description: "Keeps your mouth filled.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "penis_gag.png",
			accIcon: 0,
		},
		{
			index: 30,
			name: "skeleton mask",
			name_cap: "Skeleton mask",
			variable: "skele",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "event", "mask"],
			gender: "n",
			warmth: 0,
			cost: 2500,
			description: "For when you've a bone to pick.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "skeleton_mask.png",
			accIcon: 0,
		},
		{
			index: 31,
			name: "esoteric spectacles",
			name_cap: "Esoteric spectacles",
			variable: "esoteric",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["glasses", "esoteric"],
			gender: "n",
			warmth: 0,
			cost: 50000,
			description: "Spectacles of the hookah master.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "glasses.png",
			accIcon: 0,
		},
		{
			index: 32,
			name: "gas mask",
			name_cap: "Gas mask",
			variable: "gasmask",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 25,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "brown", "tan", "olive", "sand", "grey", "white", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["mask", "covered", "costume"],
			gender: "n",
			warmth: 10,
			cost: 20000,
			description: "Hides your identity, but may earn you some strange looks.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			accessory_layer_under: 1, /*Used to layer face items under fringe*/
			cursed: 0,
			location: 0,
			iconFile: "gas_mask.png",
			accIcon:"gas_mask_acc.png",
		},
		{
			index: 33,
			name: "eyepatch",
			name_cap: "Eyepatch",
			variable: "eyepatch",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "an",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "For sailing the high seas.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "eyepatch.png",
			accIcon: 0,
		},
		{
			index: 34,
			name: "medical eyepatch",
			name_cap: "Medical eyepatch",
			variable: "medical eyepatch",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "an",
			plural: 1,
			colour: 0,
			colour_options: ["black", "white", "grey", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "In case of emergency.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "medical_eyepatch.png",
			accIcon: 0,
		},
		{
			index: 35,
			name: "doggy muzzle",
			name_cap: "Doggy Muzzle",
			variable: "doggymuzzle",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["gag", "fetish", "covered"],
			gender: "n",
			warmth: 0,
			cost: 16000,
			description: "Keeps your dangerous mouth shut.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "doggymuzzle.png",
			accIcon: 0,
		},

		{
			index: 36,
			name: "bamboo muzzle",
			name_cap: "Bamboo muzzle",
			variable: "bamboomuzzle",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["gag", "fetish", "covered"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Keeps your dangerous mouth shut.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "bamboomuzzle.png",
			accIcon: 0,
		},
		{
			index: 37,
			name: "monocle",
			name_cap: "Monocle",
			variable: "monocle",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "grey", "steel", "blue steel", "bronze", "gold", "silver"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Makes studying easier, but you might be picked on at school.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "monocle.png",
			accIcon: "monocle_acc.png",
		},
		{
			index: 38,
			name: "islander mask",
			name_cap: "Islander mask",
			variable: "islandermask",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["mask", "covered", "costume"],
			colour_combat: 0,
			gender: "n",
			warmth: 25,
			cost: 5000,
			description: "Worn by the islanders.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "islander_mask.png",
			accIcon: 0,
		}
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.face = [
		{
			index: 3,
			name: "butterflypendant",
			name_cap: "butterflypendant", cn_name_cap: "蝴蝶饰品",
			variable: "butterflypendant",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["mask", "covered"],
			gender: "n",
			warmth: 10,
			cost: 2000,
			description: "吸引小蝴蝶。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "butterflypendant.png",
			accIcon: 0
		},
	
		{
			index: 0,
			name: "ann_yujunduan",
			name_cap: "ann_yujunduan", cn_name_cap: "与君断（面帘）",
			variable: "ann_yujunduan",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy", "dance"],
			gender: "f",
			warmth: 0,
			cost: 30000,
			description: "据说是某位著名舞姬生前最喜欢的款式，明明是跳舞时佩戴的面饰，金属蝴蝶上却浅浅刻着一柄剑。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ann_yujunduan.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "ann_snow",
			name_cap: "ann_snow", cn_name_cap: "雪满头（面帘）",
			variable: "ann_snow",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy", "dance"],
			gender: "f",
			warmth: 0,
			cost: 30000,
			description: "似乎是在红色款式之后几年发行的，金属装饰上用小字刻着“泥销骨...愿...”剩下的看不清了。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ann_snow.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "ann_huadian",
			name_cap: "Ann_huadian", cn_name_cap: "花钿",
			variable: "ann_huadian",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 23000,
			description: "中国古代女子用于面部的花朵形状的装饰物。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ann_huadian.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "ann_huadian2",
			name_cap: "Ann_huadian2", cn_name_cap: "遮面花钿",
			variable: "ann_huadian2",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy"],
			gender: "f",
			warmth: 0,
			cost: 23000,
			description: "中国古代女子用于面部的花朵形状的装饰物，通过神奇的力量掩盖身份。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ann_huadian2.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "vintagegoggoles",
			name_cap: "vintagegoggoles", cn_name_cap: "护目镜",
			variable: "vintagegoggoles",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 23000,
			description: "笨重有用。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "vintagegoggoles.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "heart shaped balloon",
			name_cap: "Heart shaped balloon", cn_name_cap: "心形气球",
			variable: "heart shaped balloon",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "一束帮着蝴蝶结的心形的气球，上面写着“Happy”。",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "heart_shaped_balloon.png",
			accIcon: 0
		},
	
	
		{
			index: 7,
			name: "catface",
			name_cap: "catface", cn_name_cap: "猫猫面具",
			variable: "catface",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy"],
			gender: "n",
			warmth: 0,
			cost: 23000,
			description: "给那些图谋不轨的人。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "catface.png",
			accIcon: 0
		},
	
		{
			index: 7,
			name: "saibow",
			name_cap: "saibow", cn_name_cap: "赛博面具",
			variable: "saibow",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy"],
			gender: "n",
			warmth: 0,
			cost: 23000,
			description: "主打就是一个潮流。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "saibow.png",
			accIcon: 0
		},
	
		{
			index: 32,
			name: "danpian",
			name_cap: "danpian", cn_name_cap: "单片眼镜",
			variable: "danpian",
			integrity: 900,
			integrity_max: 900,
			fabric_strength: 1000,
			reveal: 300,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["glasses", "formal", "stealthy", "sticky_fingers", "esoteric"],
			gender: "n",
			warmth: 0,
			cost: 50000,
			description: "一枚水晶制的单片眼镜，当你拿起它的时候好像恍惚看到了一位右眼戴着单片眼镜，身穿黑色古典长袍、头戴同色尖顶软帽的黑发黑眼，脸庞瘦削，额头宽阔的年轻男子。你不知这眼镜和那男子有何关联。",
			shop: ["clothing", "school", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "danpian.png",
			accIcon: 0
		},
	
		{
			index: 33,
			name: "jinsedanbianyanjing",
			name_cap: "jinsedanbianyanjing",
			cn_name_cap: "金色单边眼镜",
			variable: "jinsedanbianyanjing",
			integrity: 900,
			integrity_max: 900,
			fabric_strength: 1000,
			reveal: 300,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["glasses", "holy", "esoteric", "eerie"],
			gender: "n",
			warmth: 0,
			cost: 50000,
			description: "亚当是背后的掌控者，用008和004控制事件，操控世界大势按照他安排的方式走成为他成神的阶梯，他也是远古太阳神为了摆脱污染做的挣扎，被背叛后遗留的一部分权柄和理智.",
			shop: ["clothing", "school", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "jinsedanbianyanjing.png",
			accIcon: 0
		},
	
		{
			index: 96,
			name: "yan zhao",
			name_cap: "yan zhao", cn_name_cap: "单边眼罩",
			variable: "yan zhao",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "blindfold"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "一款由梅林许愿机出产的单边眼罩,不知为何看到这个单边眼罩就有一种想往脸上带的冲动.戴上后会产生摆几个羞耻度爆表pose的想法.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "yan zhao.png",
			accIcon: 0
		},
	
		{
			index: 57,
			name: "bs yan zhao",
			name_cap: "bs yan zhao", cn_name_cap: "白色眼罩", variable: "bs yan zhao",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 1000,
			reveal: 300, word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["fetish", "blindfold"],
			gender: "n",
			warmth: 0,
			cost: 50000,
			description: "一款由梅林许愿机出产的白色单边眼罩.我的苍白之瞳在燃烧,它在迸发耀眼如辰的光芒！出来吧！Pale eyes！",
			shop: ["clothing",],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			conFile: "bs yan zhao.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "eyepatch",
			name_cap: "Eyepatch", cn_name_cap: "单眼眼罩",
			variable: "eyepatch",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy"],
			gender: "n",
			warmth: 0,
			cost: 1500,
			description: "有某种神秘的力量封印在你的眼睛里……",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "eyepatch.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "bubble gum",
			name_cap: "Bubble gum", cn_name_cap: "泡泡糖",
			variable: "bubblegum",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["mask", "covered"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "便宜又好吃！",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "bubble_gum.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "peony",
			name_cap: "Peony", cn_name_cap: "花迭罗",
			variable: "peony",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 5000,
			description: "云想衣裳花想容，春风拂槛露华浓；一枝红艳露凝香，名花倾国两相欢。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "peony.png",
			accIcon: 0
		},
	
		{
			index: 34,
			name: "jin si yan jing",
			name_cap: "jin si yan jing", cn_name_cap: "格尔曼的金丝眼镜",
			variable: "jin si yan jing",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 100,
			reveal: 300,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["glasses", "esoteric"],
			gender: "n",
			warmth: 0,
			cost: 5600,
			description: "由梅林许愿机出产的金丝眼镜,没有什么作用,但是你可以尝试戴上这副眼镜去模仿那位著名的赏金猎人.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "jin si yan jing.png",
			accIcon: 0
		},
	
		{
			index: 34,
			name: "yebdcos",
			name_cap: "yebdcos", cn_name_cap: "雅儿贝德翅膀",
			variable: "yebdcos",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 100,
			reveal: 300,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["esoteric"],
			gender: "n",
			warmth: 0,
			cost: 5600,
			description: "吾乃侍奉无上至尊之人，作为先锋而来，宣告汝等的死亡。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "yebdcos.png",
			accIcon: 0
		},
	
		{
			index: 22,
			name: "verosika",
			name_cap: "verosika", cn_name_cap: "爱心墨镜",
			variable: "verosika",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "充满特色的爱心墨镜。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "verosika mojing.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "xhudie",
			name_cap: "xhudie", cn_name_cap: "蝴蝶眼罩",
			variable: "xhudie",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["mask", "covered"],
			gender: "n",
			warmth: 10,
			cost: 2000,
			description: "吸引小蝴蝶。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "xhudie.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "hdyanzbao",
			name_cap: "hdyanzbao", cn_name_cap: "眼罩",
			variable: "hdyanzbao",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["mask", "covered"],
			gender: "n",
			warmth: 10,
			cost: 2000,
			description: "酷。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "hdyanzbao.png",
			accIcon: 0
		}
	];

	setup.moddedClothes.face.forEach((x, i) => (x.index = setup.clothes.face.length + i));
	setup.clothes.face.push(...setup.moddedClothes.face);
}
window.initFace = initFace;
