/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites. */
function initLegs() {
	setup.clothes.legs = [
		{
			index: 0,
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			state: 0,
			state_base: 0,
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},

		{
			index: 1,
			name: "tights",
			name_cap: "Tights",
			variable: "tights",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 5,
			cost: 1000,
			description: "They don't conceal much.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "tights.png",
			accIcon: 0,
		},

		{
			index: 2,
			name: "boy's gym socks",
			name_cap: "Boy's gym socks",
			variable: "boysgymsocks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school"],
			gender: "m",
			femininity: -100,
			warmth: 15,
			cost: 500,
			description: "Cushioned and breathable.",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "boys_gym_socks.png",
			accIcon: 0,
		},

		{
			index: 3,
			name: "girl's gym socks",
			name_cap: "Girl's gym socks",
			variable: "girlsgymsocks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school"],
			gender: "f",
			femininity: 100,
			warmth: 15,
			cost: 500,
			description: "Cushioned and breathable.",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "girls_gym_socks.png",
			accIcon: 0,
		},

		{
			index: 4,
			name: "stockings",
			name_cap: "Stockings",
			variable: "stockings",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 15,
			cost: 1500,
			description: "Attractive and alluring.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "stockings.png",
			accIcon: 0,
		},

		{
			index: 5,
			name: "fishnet stockings",
			name_cap: "Fishnet stockings",
			variable: "fishnetstockings",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 1500,
			description: "Attractive and alluring.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "fishnet_stockings.png",
			accIcon: 0,
		},

		{
			index: 6,
			name: "fishnet tights",
			name_cap: "Fishnet tights",
			variable: "fishnettights",
			integrity: 25,
			integrity_max: 25,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 1700,
			description: "Attractive and alluring.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "fishnet_tights.png",
			accIcon: 0,
		},

		{
			index: 7,
			name: "garter stockings",
			name_cap: "Garter stockings",
			variable: "garterstockings",
			integrity: 15,
			integrity_max: 15,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 20,
			cost: 4000,
			description: "Sexy.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "garter_stockings.png",
			accIcon: 0,
		},

		{
			index: 8,
			name: "legwarmers",
			name_cap: "Legwarmers",
			variable: "legwarmers",
			integrity: 25,
			integrity_max: 25,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 70,
			cost: 1500,
			description: "Cosy.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "legwarmers.png",
			accIcon: 0,
		},

		{
			index: 9,
			name: "christmas leg warmers",
			name_cap: "Christmas leg warmers",
			variable: "christmas",
			integrity: 25,
			integrity_max: 25,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 70,
			cost: 2500,
			description: "Festive.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "christmas_leg_warmers.png",
		},

		{
			index: 10,
			name: "gold anklets",
			name_cap: "Gold anklets",
			variable: "goldanklets",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "n",
			warmth: 0,
			cost: 25000,
			description: "Exotic and eye-catching.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "gold_anklets.png",
			accIcon: 0,
		},

		{
			index: 11,
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			state: 0,
			state_base: 0,
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 12,
			name: "striped thighhighs",
			name_cap: "Striped thighhighs",
			variable: "stripedthighhighs",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 20,
			cost: 3000,
			description: "Brimming with personality.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "striped_thighhighs.png",
			accIcon: "striped_thighhighs_acc.png",
		},

		{
			index: 13,
			name: "ankle socks",
			name_cap: "Ankle socks",
			variable: "anklesocks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["school", "athletic"],
			gender: "n",
			femininity: 0,
			warmth: 10,
			cost: 500,
			description: "Perfect for sport.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ankle_socks.png",
			accIcon: "ankle_socks_acc.png",
		},

		{
			index: 14,
			name: "plain thighhighs",
			name_cap: "Plain thighhighs",
			variable: "plainthighhighs",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 20,
			cost: 2500,
			description: "Simple and cute.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "striped_thighhighs.png",
			accIcon: 0,
		},

		{
			index: 15,
			name: "cow socks",
			name_cap: "Cow socks",
			variable: "cow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			femininity: -0,
			warmth: 15,
			cost: 1000,
			description: "Cute cow print.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cow_socks.png",
			accIcon: 0,
		},

		{
			index: 16,
			name: "nurse socks",
			name_cap: "Nurse socks",
			variable: "nursesocks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 100,
			warmth: 15,
			cost: 900,
			description: "Worn by nurses at the local hospital.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "nurse_socks.png",
			accIcon: 0,
		},

		{
			index: 17,
			name: "ribbon stockings",
			name_cap: "Ribbon stockings",
			variable: "ribbonstockings",
			integrity: 15,
			integrity_max: 15,
			fabric_strength: 20,
			reveal: 300,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 20,
			cost: 4000,
			description: "Cute.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "ribbon_stockings.png",
			accIcon: "ribbon_stockings_acc.png",
		},

		{
			index: 18,
			name: "patterned dress socks",
			name_cap: "Patterned dress socks",
			variable: "twirly socks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 20,
			cost: 1200,
			description: "Men's dress socks. Masculine, yet playful.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "twirly_socks.png",
			accIcon: "twirly_socks_acc.png",
		},

		{
			index: 19,
			name: "polka dot socks",
			name_cap: "Polka dot socks",
			variable: "polka socks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 20,
			cost: 1200,
			description: "Patterned dress socks. Masculine, yet playful.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "polka_socks.png",
			accIcon: "polka_socks_acc.png",
		},

		{
			index: 20,
			name: "sports socks",
			name_cap: "Sports socks",
			variable: "sports socks short",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal", "athletic"],
			gender: "m",
			femininity: -100,
			warmth: 20,
			cost: 500,
			description: "Cushioned and breathable.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "short_sport.png",
			accIcon: "short_sport_acc.png",
		},

		{
			index: 21,
			name: "knee-high sports socks",
			name_cap: "Knee-high sports socks",
			variable: "sports socks long",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal", "athletic"],
			gender: "m",
			femininity: -300,
			warmth: 20,
			cost: 800,
			description: "Cushioned and breathable.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "long_sport.png",
			accIcon: "long_sport_acc.png",
		},

		{
			index: 22,
			name: "rib-knit socks",
			name_cap: "Rib-knit socks",
			variable: "striped socks long",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "knees",
			state_base: "knees",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 20,
			cost: 1200,
			description: "Men's ribbed socks, for his pleasure.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "long_stripe.png",
			accIcon: 0,
		},

		{
			index: 23,
			name: "Rib-knit ankle socks",
			name_cap: "Rib-knit ankle socks",
			variable: "striped socks short",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 20,
			cost: 1000,
			description: "Men's ribbed socks, for his pleasure.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			cursed: 0,
			location: 0,
			iconFile: "short_stripe.png",
			accIcon: 0,
		},

		{
			index: 24,
			name: "Striped kneehighs",
			name_cap: "Striped kneehighs",
			variable: "striped kneehighs",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 20,
			cost: 2000,
			description: "Brimming with personality.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "striped_kneehighs.png",
			accIcon: "striped_kneehighs_acc.png",
		},

		{
			index: 25,
			name: "sheer leggings",
			name_cap: "Sheer leggings",
			variable: "sheerleggings",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 50,
			word: "n",
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_combat: "black",
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "dance", "athletic"],
			gender: "f",
			femininity: 200,
			warmth: 25,
			cost: 1000,
			description: "Too translucent to wear alone.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "leggings.png",
			accIcon: 0,
		}
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.legs = [
		{
			index: 3,
			name: "whitesocks",
			name_cap: "whitesocks", cn_name_cap: "白色花边袜",
			variable: "whitesocks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school"],
			gender: "f",
			femininity: 100,
			warmth: 15,
			cost: 500,
			description: "可爱的白色花边袜。",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "whitesocks.png",
			accIcon: 0
		},
	
		{
			index: 4,
			name: "balckstockings",
			name_cap: "balckstockings", cn_name_cap: "皮扣短袜袜",
			variable: "balckstockings",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 15,
			cost: 1500,
			description: "可爱诱惑。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "balckstockings.png",
			accIcon: 0
		},
	
		{
			index: 19,
			name: "bai wa;s gym socks",
			name_cap: "Girl&#39;s gym socks", cn_name_cap: "白色长袜",
			variable: "bai wa",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 15,
			cost: 500,
			description: "太阳那个爱着哟～。",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "bai wa.png",
			accIcon: 0
		},
	
		{
			index: 21,
			name: "y2kleg",
			name_cap: "y2kleg", cn_name_cap: "堆堆袜",
			variable: "y2kleg",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 15,
			cost: 500,
			description: "亚比风堆堆袜哟。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "y2kleg.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "aduoduowa",
			name_cap: "aduoduowa", cn_name_cap: "堆堆袜二",
			variable: "aduoduowa",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["school"],
			gender: "f",
			femininity: 100,
			warmth: 15,
			cost: 500,
			description: "可爱的堆堆袜。",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "aduoduowa.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "ann_dawn",
			name_cap: "Ann_dawn", cn_name_cap: "黎明短袜",
			variable: "ann_dawn",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["school", "athletic"],
			gender: "n",
			femininity: 0,
			warmth: 10,
			cost: 4500,
			description: "“会有人看到的，我们口中的黎明。”",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "ann_dawn.png",
			accIcon: "ann_dawn.png"
		},
	
		{
			index: 2,
			name: "lanlanlu sock",
			name_cap: "Lanlanlu sock", cn_name_cap: "开心长袜",
			variable: "lanlanlu",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school", "normal"],
			gender: "f",
			femininity: 200,
			warmth: 30,
			cost: 9900,
			description: "洋溢着可可爱爱。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "lanlanlu legs.png",
			accIcon: 0
		},
	
		{
			index: 13,
			name: "duan wa",
			name_cap: "duan wa", cn_name_cap: "中筒袜",
			variable: "duan wa",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["school", "athletic"],
			gender: "n",
			femininity: 0,
			warmth: 10,
			cost: 500,
			description: "手感细腻，亲肤贴合，给你一双有温度的袜子，现在购买不需要648，不需要328，只要198，还在等什么快来抢购吧！",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "duan wa.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "black thigh socks",
			name_cap: "Black thigh socks", cn_name_cap: "黑色长筒袜",
			variable: "black thigh socks",
			integrity: 80,
			integrity_max: 80,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_combat: 0,
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 20,
			cost: 10000,
			description: "一双黑色的长筒袜，长度刚好到大腿。袜子口还有一行白色丝线绣着的文字“Love”。",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "black_thigh_socks.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "luotywz",
			name_cap: "luotywz", cn_name_cap: "洛天依长袜",
			variable: "luotywz",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school", "normal"],
			gender: "f",
			femininity: 200,
			warmth: 30,
			cost: 9900,
			description: "用来cos洛天依。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "luotywz.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "anwgirl&#39;s gym socks",
			name_cap: "anwgirl&#39;s gym socks", cn_name_cap: "潮流短堆袜",
			variable: "anwgirlsgymsocks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school"],
			gender: "f",
			femininity: 100,
			warmth: 15,
			cost: 500,
			description: "材质柔软舒服且透气。",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "anwgirlsgymsocks.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "bengdaiwa",
			name_cap: "bengdaiwa", cn_name_cap: "白短袜",
			variable: "bengdaiwa",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["school", "normal"],
			gender: "f",
			femininity: 200,
			warmth: 30,
			cost: 9900,
			description: "绷带缠绕。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "bengdaiwa.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "madoka socks",
			name_cap: "Madoka socks", cn_name_cap: "鹿目圆香",
			variable: "madoka socks",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			state: "ankles",
			state_base: "ankles",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "f",
			femininity: 30,
			warmth: 20,
			cost: 4000,
			description: "从今以后就永远在一起了。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "madoka_feet.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "black and white pile socks",
			name_cap: "Black and white pile socks", cn_name_cap: "黑白条纹堆堆袜",
			variable: "black and white pile socks",
			integrity: 80,
			integrity_max: 80,
			fabric_strength: 20,
			reveal: 100,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			colour_sidebar: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 40,
			cost: 10000,
			description: "这不是一双袜子，而是两双，所以能给你双倍的保暖。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "black_and_white_pile_socks.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "zhiye stockings",
			name_cap: "Zhiye stockings", cn_name_cap: "织夜长袜",
			variable: "zhiyestockings",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 1500,
			description: "朦胧的昏暗。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "zhiye_stockings.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "duanwaaaa",
			name_cap: "duanwaaaa", cn_name_cap: "丰川祥子短袜",
			variable: "duanwaaaa",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 1500,
			description: "我听到敲门声了。我知道他们终究要来的。他们要来带走他。我不会让那发生。我已经把他放走了,他该回到海中去。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "duanwaaaa.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "miemietao",
			name_cap: "miemietao", cn_name_cap: "咩咩长袜",
			variable: "miemietao",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			state: "thighs",
			state_base: "thighs",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 1500,
			description: "你才是幼稚鬼呢。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "miemietao.png",
			accIcon: 0
		},
	];

	setup.moddedClothes.legs.forEach((x, i) => (x.index = setup.clothes.legs.length + i));
	setup.clothes.legs.push(...setup.moddedClothes.legs);
}
window.initLegs = initLegs;
