/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites. */
function initHead() {
	setup.clothes.head = [
		{
			index: 0,
			name: "naked",
			name_cap: "Naked",
			variable: "naked",
			integrity: 0,
			integrity_max: 0,
			fabric_strength: 0,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},

		{
			index: 1,
			name: "hairpin",
			name_cap: "Hairpin",
			variable: "hairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "Greatly accelerates hair growth.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "hairpin.png",
			accIcon: 0,
		},

		{
			index: 2,
			name: "beanie",
			name_cap: "Beanie",
			variable: "beanie",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			warmth: 35,
			cost: 3000,
			description: "Makes status rise faster at school.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "beanie.png",
			accIcon: 0,
		},

		{
			index: 3,
			name: "bunny ears",
			name_cap: "Bunny ears",
			variable: "bunnyears",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "n",
			warmth: 0,
			cost: 3000,
			description: "Cute ears on a headband. Part of a bunny outfit.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "bunny_ears.png",
			accIcon: 0,
		},

		{
			index: 4,
			name: "nun's veil",
			name_cap: "Nun's veil",
			variable: "nun",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			type: ["holy", "costume"],
			gender: "f",
			femininity: 200,
			warmth: 15,
			cost: 2500,
			description: "Protects your hair from unwanted attentions.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "nuns_veil.png",
			accIcon: 0,
		},

		{
			index: 5,
			name: "bow",
			name_cap: "Bow",
			variable: "bow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 900,
			description: "Cute.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "bow.png",
			accIcon: 0,
		},

		{
			index: 6,
			name: "cap",
			name_cap: "Cap",
			variable: "cap",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "shade"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "Shields you from the sun.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cap.png",
			accIcon: 0,
		},

		{
			index: 7,
			name: "witch hat",
			name_cap: "Witch hat",
			variable: "witch",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 20,
			cost: 3000,
			description: "Patchy and fragrant.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "witch_hat.png",
			accIcon: "witch_hat_acc.png",
		},

		{
			index: 8,
			name: "christmas hat",
			name_cap: "Christmas hat",
			variable: "christmas",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 40,
			cost: 5000,
			description: "'Tis the season.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "christmas_hat.png",
		},

		{
			index: 9,
			name: "chef hat",
			name_cap: "Chef hat",
			variable: "chef",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "n",
			warmth: 5,
			cost: 5000,
			description: "Keeps cream out of your hair.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "chef_hat.png",
		},

		{
			index: 10,
			name: "cowboy hat",
			name_cap: "Cowboy hat",
			variable: "cowboy",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 10,
			cost: 8000,
			description: "Protects you from the sun.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "cowboy_hat.png",
			accIcon: 0,
		},

		{
			index: 11,
			name: "fedora",
			name_cap: "Fedora",
			variable: "fedora",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "shade"],
			gender: "m",
			femininity: -100,
			warmth: 10,
			cost: 5000,
			description: "Suave.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "fedora.png",
		},

		{
			index: 12,
			name: "beatnik hat",
			name_cap: "Beatnik hat",
			variable: "beatnik",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["cool"],
			gender: "m",
			femininity: -100,
			warmth: 10,
			cost: 8000,
			description: "Conforming isn't your style.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "beatnik_hat.png",
		},

		{
			index: 13,
			name: "sou'wester",
			name_cap: "Sou'wester",
			variable: "sou",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["rainproof"],
			gender: "n",
			warmth: 15,
			cost: 4000,
			description: "Keeps the rain off.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "souwester.png",
		},

		{
			index: 14,
			name: "flower crown",
			name_cap: "Flower crown",
			variable: "flower",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 0,
			description: "Floral.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "flower_crown.png",
		},

		{
			index: 15,
			name: "backwards cap",
			name_cap: "Backwards cap",
			variable: "backwardscap",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "shade"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "Protects your neck from the sun.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "backwards_cap.png",
			accIcon: 0,
		},

		{
			index: 16,
			name: "alice band",
			name_cap: "Alice band",
			variable: "alice",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 1100,
			description: "Holds your hair back.",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "alice_band.png",
			accIcon: 0,
		},

		{
			index: 17,
			name: "straw hat",
			name_cap: "Straw hat",
			variable: "straw",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "shade"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 700,
			description: "Keeps the sun off.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "straw_hat.png",
			accIcon: "straw_hat_acc.png",
		},

		{
			index: 18,
			name: "straw flower hat",
			name_cap: "Straw flower hat",
			variable: "strawflower",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1500,
			description: "Keeps the sun off.",
			shop: [],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 19,
			name: "maid band",
			name_cap: "Maid band",
			variable: "maid",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["maid", "costume", "serving"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 1200,
			description: "For looking cute while cleaning.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "maid_band.png",
			accIcon: 0,
		},

		{
			index: 20,
			name: "bun covers",
			name_cap: "Bun covers",
			variable: "bun",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 5000,
			description: "Exotic.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "bun_covers.png",
			accIcon: 0,
		},

		{
			index: 21,
			name: "headband",
			name_cap: "Headband",
			variable: "band",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1100,
			description: "Keeps hair from your eyes.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "headband.png",
			accIcon: 0,
		},

		{
			index: 22,
			name: "feathered cap",
			name_cap: "Feathered cap",
			variable: "feathered",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "shade"],
			gender: "m",
			femininity: -200,
			warmth: 10,
			cost: 2200,
			description: "For when you have something to be proud of.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "feathered_cap.png",
			accIcon: 0,
		},

		{
			index: 23,
			name: "large sailor's hat",
			name_cap: "Large sailor's hat",
			variable: "sailorbig",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "m",
			femininity: -200,
			warmth: 10,
			cost: 3000,
			description: "Shields you from the sun.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "large_sailors_hat.png",
			accIcon: 0,
		},

		{
			index: 24,
			name: "small sailor's hat",
			name_cap: "Small sailor's hat",
			variable: "sailorsmall",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "m",
			femininity: -200,
			warmth: 10,
			cost: 2000,
			description: "Shields you from the sun.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "small_sailors_hat.png",
			accIcon: 0,
		},

		{
			index: 25,
			name: "football helmet",
			name_cap: "Football helmet",
			variable: "football",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "athletic"],
			gender: "m",
			femininity: -200,
			warmth: 30,
			cost: 2000,
			description: "Protective headwear. Used in a foreign sport.",
			shop: ["clothing", "school", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "football_helmet.png",
			accIcon: 0,
		},

		{
			index: 26,
			name: "big bow",
			name_cap: "Big bow",
			variable: "bigbow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 0,
			cost: 1400,
			description: "Very cute.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "big_bow.png",
			accIcon: 0,
		},

		{
			index: 27,
			name: "riding helmet",
			name_cap: "Riding helmet",
			variable: "riding",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "athletic", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 30,
			cost: 16000,
			description: "Protective headwear.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "riding_helmet.png",
			accIcon: 0,
		},

		{
			index: 28,
			name: "top hat",
			name_cap: "Top hat",
			variable: "top",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "formal"],
			gender: "m",
			femininity: -200,
			warmth: 10,
			cost: 6000,
			description: "Old fashioned sophistication.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "top_hat.png",
			accIcon: 0,
		},

		{
			index: 29,
			name: "umbrella hat",
			name_cap: "Umbrella hat",
			variable: "umbrella",
			integrity: 120,
			integrity_max: 120,
			fabric_strength: 10,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["rainproof", "shade"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "Keeps the rain off, but attracts attention.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "umbrella_hat.png",
			accIcon: 0,
		},

		{
			index: 30,
			name: "racing helmet",
			name_cap: "Racing helmet",
			variable: "racing",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "athletic", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 20,
			cost: 15000,
			description: "For serious riding.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "racing_helmet.png",
			accIcon: 0,
		},

		{
			index: 31,
			name: "feathered hair clip",
			name_cap: "Feathered hair clip",
			variable: "featheredhairclip",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "eerie"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "Made with real feathers.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "feathered_hair_clip.png",
			accIcon: 0,
		},

		{
			index: 32,
			name: "hoodie hood",
			name_cap: "Hoodie hood",
			variable: "hoodie",
			integrity: 180,
			integrity_max: 180,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			colour_options: [
				"black",
				"blue steel",
				"grey",
				"white",
				"light pink",
				"light blue",
				"light green",
				"sand",
				"red",
				"pink",
				"purple",
				"tangerine",
				"teal",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal"],
			set: "hoodie",
			gender: "n",
			warmth: 20,
			cost: 0,
			description: "Portable social isolator.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"blue steel",
				"grey",
				"white",
				"light pink",
				"light blue",
				"light green",
				"sand",
				"red",
				"pink",
				"purple",
				"tangerine",
				"teal",
				"custom",
			],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "secondary",
			cursed: 0,
			location: 0,
			outfitSecondary: ["upper", "hoodie"],
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 33,
			name: "tam o' shanter",
			name_cap: "Tam o' shanter",
			variable: "tam",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			hood: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 25,
			cost: 4500,
			description: "For honest men and bonnie lasses.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "tam_o_shanter.png",
			accIcon: 0,
		},

		{
			index: 34,
			name: "cat hat",
			name_cap: "Cat hat",
			variable: "cat",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			hood: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 25,
			cost: 3000,
			description: "Whiskers not included.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cat_hat.png",
			accIcon: 0,
		},

		{
			index: 35,
			name: "monster hood",
			name_cap: "Monster hood",
			variable: "monster",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			colour_options: ["apocalypse", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			set: "monsterhoodie",
			gender: "n",
			warmth: 25,
			cost: 0,
			description: "Rawr.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "",
			outfitSecondary: ["upper", "monster hoodie"],
			accIcon: 0,
		},

		{
			index: 36,
			name: "kitty ears",
			name_cap: "Kitty ears",
			variable: "kitty",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "n",
			one_piece: 0,
			plural: 1,
			hood: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "n",
			warmth: 25,
			cost: 1500,
			description: "Cute.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "kitty_ears.png",
			accIcon: "kitty_ears_acc.png",
		},

		{
			index: 37,
			name: "mini snowman",
			name_cap: "Mini snowman",
			variable: "minisnowman",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 5,
			reveal: 1,
			word: "n",
			one_piece: 0,
			plural: 0,
			hood: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 40,
			cost: 2500,
			description: "Surprisingly warm.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "mini_snowman.png",
			accIcon: 0,
		},

		{
			index: 38,
			name: "cow onesie hood",
			name_cap: "Cow onesie hood",
			variable: "cowonesie",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			type: ["sleep", "costume"],
			gender: "n",
			warmth: 40,
			cost: 0,
			description: "Snug.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "",
			outfitSecondary: ["upper", "cow onesie"],
			accIcon: 0,
		},

		{
			index: 39,
			name: "baseball cap",
			name_cap: "Baseball cap",
			variable: "baseball",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["athletic", "shade"],
			gender: "n",
			warmth: 0,
			cost: 6000,
			description: "Shields you from the sun.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "baseball_cap.png",
			accIcon: "baseball_cap_acc.png",
		},

		{
			index: 40,
			name: "rose",
			name_cap: "Rose",
			variable: "rose",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["red", "white", "pink", "light pink", "purple", "yellow", "tangerine", "black", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 2000,
			description: "Smells fresh.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "rose.png",
			accIcon: "rose_acc.png",
		},

		{
			index: 41,
			name: "scarecrow hat",
			name_cap: "Scarecrow hat",
			variable: "scarecrow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "Worn by the empty-headed.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "scarecrow_hat.png",
		},

		{
			index: 42,
			name: "fish hairpin",
			name_cap: "Fish hairpin",
			variable: "fishhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 500,
			description: "Feels like real bone.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "fish_hairpin.png",
			accIcon: 0,
		},

		{
			index: 43,
			name: "pink nurse hat",
			name_cap: "Pink nurse hat",
			variable: "pinknurse",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1200,
			description: "Worn by nurses at the hospital.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "pink_nurse.png",
			accIcon: 0,
		},

		{
			index: 44,
			name: "plastic nurse hat",
			name_cap: "Plastic nurse hat",
			variable: "plasticnurse",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "unstealthy"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1800,
			description: "Easy to clean.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "plastic_nurse.png",
			accIcon: 0,
		},

		{
			index: 45,
			name: "transparent nurse hat",
			name_cap: "Transparent nurse hat",
			variable: "transparentnurse",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 2400,
			description: "Easy to clean.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "transparent_nurse.png",
			accIcon: 0,
		},

		{
			index: 46,
			name: "bunny headband",
			name_cap: "Bunny headband",
			variable: "bunband",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 3000,
			description: "Two cute bun tufts on a band.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "bunny_headband.png",
			accIcon: 0,
		},

		{
			index: 47,
			name: "daisy",
			name_cap: "Daisy",
			variable: "daisy",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 100,
			description: "A single daisy, its stem can be threaded through hair.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "daisy.png",
		},

		{
			index: 48,
			name: "spirit mask",
			name_cap: "Spirit mask",
			variable: "spiritmask",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume", "eerie"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 6000,
			description: "Doesn't fit over your face.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "spirit_mask.png",
			accIcon: "spirit_mask_acc.png",
		},

		{
			index: 49,
			name: "raccoon cap",
			name_cap: "Raccoon cap",
			variable: "furcap m",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_combat: 0,
			colour_options: ["black", "brown", "grey", "tan", "sand", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 35,
			cost: 2000,
			description: "Keeps your head warm.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "brown", "grey", "tan", "sand", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "furcapm.png",
			accIcon: "furcapm_acc.png",
		},

		{
			index: 50,
			name: "fur cap",
			name_cap: "Fur cap",
			variable: "furcap f",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_combat: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 35,
			cost: 6000,
			description: "Warm and fashionable.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "furcapf.png",
			accIcon: "furcapf_acc.png",
		},

		{
			index: 51,
			name: "conical hat",
			name_cap: "Conical hat",
			variable: "conicalhat",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "shade", "rainproof"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 700,
			description: "Keeps the sun off.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 1,
			back_img: 1,
			cursed: 0,
			location: 0,
			iconFile: "conical_hat.png",
		},

		{
			index: 52,
			name: "cat hoodie hood",
			name_cap: "Cat hoodie hood",
			variable: "cat hoodie",
			integrity: 180,
			integrity_max: 180,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue steel", "grey", "white", "light pink", "light blue", "light green", "sand", "red", "pink", "purple", "tangerine", "teal", "custom"],
			colour_sidebar: "primary",
			type: ["normal"],
			set: "hoodie",
			gender: "n",
			warmth: 20,
			cost: 0,
			description: "You know, like nya?",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			cursed: 0,
			location: 0,
			outfitSecondary: ["upper", "cat hoodie"],
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 53,
			name: "bat beanie",
			name_cap: "Bat beanie",
			variable: "bat beanie",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "n",
			warmth: 35,
			cost: 4500,
			description: "Spooky cute.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "bat_beanie.png",
			accIcon: "bat_beanie_acc.png",
		},

		{
			index: 54,
			name: "mini pumpkin",
			name_cap: "Mini pumpkin",
			variable: "jackolantern",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 5,
			reveal: 1,
			word: "n",
			one_piece: 0,
			plural: 0,
			hood: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 40,
			cost: 2500,
			description: "All the charm of a jack o'lantern, without the impermanence.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "jackolantern.png",
			accIcon: 0,
		},

		{
			index: 55,
			name: "butterfly hairpin",
			name_cap: "Butterfly hairpin",
			variable: "butterflyhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1500,
			description: "Indistinguishable from a real butterfly.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_combat: "black",
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "butterfly_hairpin.png",
			accIcon: "butterfly_hairpin_acc.png",
		},

		{
			index: 56,
			name: "star hairpin",
			name_cap: "Star hairpin",
			variable: "starhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "Catches light to produce a twinkling effect.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "star_hairpin.png",
			accIcon: "star_hairpin_acc.png",
		}
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.head = [
		{
			index: 1,
			name: "bunnyhairpin",
			name_cap: "bunnyhairpin", cn_name_cap: "兔子发卡",
			variable: "bunnyhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "可以让头发长的快的可爱兔子发卡。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "bunnyhairpin.png",
			accIcon: 0
		},
	
		{
			index: 29,
			name: "cuteumbrella",
			name_cap: "cuteumbrella", cn_name_cap: "可爱伞帽",
			variable: "cuteumbrella",
			integrity: 120,
			integrity_max: 120,
			fabric_strength: 10,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["rainproof", "shade"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "能防止被雨淋湿，非常可爱。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "cuteumbrella.png",
			accIcon: 0
		},
	
		{
			index: 49,
			name: "jin lian",
			name_cap: "jin lian band", cn_name_cap: "金莲",
			variable: "jin lian",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "f",
			gender: "n",
			warmth: 0,
			cost: 1200,
			description: "｜+++帝释天的支配性｜。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "jin lian.png",
			accIcon: 0
		},
	
		{
			index: 5,
			name: "hairka",
			name_cap: "hairka", cn_name_cap: "豪华发卡",
			variable: "hairka",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 900,
			description: "豪华可爱。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "hairka.png",
			accIcon: 0
		},
	
		{
			index: 12,
			name: "bluehat",
			name_cap: "bluehat", cn_name_cap: "蓝色军帽",
			variable: "bluehat",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["cool"],
			gender: "m",
			femininity: -100,
			warmth: 10,
			cost: 8000,
			description: "英姿煞爽。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "bluehat.png"
		},
	
		{
			index: 1,
			name: "ctjpin",
			name_cap: "ctjpin", cn_name_cap: "超天酱发卡",
			variable: "ctjpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "升天～",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "ctjpin.png",
			accIcon: 0
		},
	
		{
			index: 5,
			name: "headphones",
			name_cap: "headphones", cn_name_cap: "头戴式耳机",
			variable: "headphones",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 900,
			description: "可爱潮流的头戴式猫耳耳机。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "headphones.png",
			accIcon: 0
		},
	
		{
			index: 7,
			name: "ahewitch hat",
			name_cap: "ahewitch hat", cn_name_cap: "新女巫帽",
			variable: "ahewitch",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 20,
			cost: 3000,
			description: "女巫的帽子，散发出浓郁的芳香。",
			shop: ["clothing", "forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "ahewitch_hat.png",
			accIcon: "ahewitch_hat_acc.png"
		},
	
		{
			index: 1,
			name: "ashizijia",
			name_cap: "ashizijia", cn_name_cap: "十字夹",
			variable: "ashizijia",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "亚梦同款发卡。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "ashizijia.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "ashizijiajj",
			name_cap: "ashizijiajj", cn_name_cap: "十字夹揪揪",
			variable: "ashizijiajj",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "配合十字夹用的可爱揪揪。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "ashizijiajj.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "afagu",
			name_cap: "afagu", cn_name_cap: "普通发箍",
			variable: "afagu",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "平平无奇但可爱。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "afagu.png",
			accIcon: 0
		},
	
		{
			index: 22,
			name: "anfeathered cap",
			name_cap: "anfeathered cap", cn_name_cap: "羽毛饰品",
			variable: "anfeathered",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["sleep", "shade"],
			gender: "m",
			femininity: 200,
			warmth: 10,
			cost: 2200,
			description: "搭配蕾丝睡衣的小羽毛。",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "anfeathered.png",
			accIcon: 0
		},
	
		{
			index: 8,
			name: "anchristmas hat",
			name_cap: "anchristmas hat", cn_name_cap: "配套圣诞帽",
			variable: "anchristmas",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 40,
			cost: 5000,
			description: "欢度佳节。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "anchristmas_hat.png"
		},
	
		{
			index: 1,
			name: "ajiandan",
			name_cap: "ajiandan", cn_name_cap: "煎蛋发卡",
			variable: "ajiandan",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "好吃～",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "ajiandan.png",
			accIcon: 0
		},
	
	
		{
			index: 40,
			name: "anrose",
			name_cap: "anrose", cn_name_cap: "玫瑰花饰品",
			variable: "anrose",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["red", "white", "pink", "light pink", "purple", "yellow", "tangerine", "black", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 2000,
			description: "闻起来像刚摘的一样。",
			shop: ["clothing", "forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "anrose.png",
			accIcon: "anrose_acc.png"
		},
	
		{
			index: 29,
			name: "sunbrella hat",
			name_cap: "sunbrella hat", cn_name_cap: "太阳伞帽",
			variable: "sunbrella",
			integrity: 120,
			integrity_max: 120,
			fabric_strength: 10,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["rainproof", "shade"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "能防止被雨淋湿与遮阳。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "sunbrella.png",
			accIcon: 0
		},
	
		{
			index: 56,
			name: "demon bobby pin",
			name_cap: "Demon bobby pin", cn_name_cap: "小恶魔发夹",
			variable: "demon bobby pin",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 3000,
			description: "小小的恶魔翅膀，说不定有一天也能飞起来。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "demonbobbypin.png",
			accIcon: 0
		},
	
	
		{
			index: 65,
			name: "lxzts",
			name_cap: "lxzts", cn_name_cap: "因提瓦特",
			variable: "lxzts",
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 100,
			description: "异世界的奇特花朵，只在故乡变回柔软。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lxzts.png",
		},
	
		{
			index: 65,
			name: "xiaofuhead",
			name_cap: "xiaofuhead", cn_name_cap: "天行学院蝴蝶结",
			variable: "xiaofuhead",
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "white",
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 100,
			description: "我不知道我有没有心，但我能看见你的心，我愿用尽我的一切。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "xiaofuhead.png",
		},
	
		{
			index: 1,
			name: "polka dot bow",
			name_cap: "Polka dot bow", cn_name_cap: "波点蝴蝶结",
			variable: "polka dot bow",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 5000,
			description: "印着白色波点的蝴蝶结，蓬松又可爱。",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "polka_dot_bow.png",
			accIcon: 0
		},
	
		{
			index: 65,
			name: "luotyts",
			name_cap: "luotyts", cn_name_cap: "洛天依头饰",
			variable: "luotyts",
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 100,
			description: "用来cos洛天依。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "luotyts.png",
		},
	
		{
			index: 224,
			name: "manyangyang",
			name_cap: "Manyangyang",
			cn_name_cap: "慢羊羊村长",
			variable: "manyangyang",
			integrity_max: 50,
			integrity: 50,
			fabric_strength: 20,
			reveal: 50,
			word: "a",
			one_piece: 0,
			plural: 0,
			hood: 0,
			mask_img: 0,
			mask_img_ponytail: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 500,
			description: "偷偷揪掉慢羊羊村长头上的叶子会发生什么事呢？",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			back_img_colour: 0,
			cursed: 0,
			location: 0,
			iconFile: "manyangyang.png",
			accIcon: "manyangyang_acc.png",
			mainImage: 1,
		},
	
		{
			index: 75,
			name: "li mao",
			name_cap: "li mao", cn_name_cap: "五海野玫瑰的礼貌",
			variable: "li mao",
			integrity: 900,
			ntegrity_max: 900,
			fabric_strength: 1000,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["formal", "stealthy"],
			gender: "m",
			femininity: -200,
			warmth: 10,
			cost: 6000,
			description: "一顶精致而古典的礼貌，当你触碰到它时你好似听到有人在你耳边低语念诵着什么，耳畔的声音从模糊逐渐变得清晰 你听清了他们在说什么不属于这个时代的愚者；灰雾之上的神秘主宰；执掌好运的黑黄之王。当他们的话语消散后，你才骤然惊醒。",
			shop: ["clothing", "adult", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			back_img_colour: 0,
			cursed: 0,
			location: 0,
			iconFile: "li mao.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "star hairpin",
			name_cap: "Star hairpin", cn_name_cap: "星星发卡",
			variable: "starhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 1500,
			description: "一闪一闪亮晶晶。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "star_hairpin.png",
			accIcon: 0
		},
	
		{
			index: 4,
			name: "earmuff",
			name_cap: "Ear muff", cn_name_cap: "耳罩",
			variable: "earmuff",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 30,
			cost: 3500,
			description: "毛茸茸的。保护你的耳朵。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "ear_muff.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "anwbunnyears",
			name_cap: "anwbunnyears", cn_name_cap: "毛茸茸兔儿",
			variable: "anwbunnyears",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 1500,
			description: "毛茸茸哒。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "anwbunnyears.png",
			accIcon: 0
		},
	
		{
			index: 12,
			name: "anwbeatnik",
			name_cap: "anwbeatnik", cn_name_cap: "贝雷帽",
			variable: "anwbeatnik",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			femininity: 0,
			warmth: 10,
			cost: 8000,
			description: "妥协不是你的风格。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "anwbeatnik.png"
		},
	
		{
			index: 2,
			name: "anwhairpin",
			name_cap: "anwhairpin", cn_name_cap: "可爱发卡",
			variable: "anwhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 1500,
			description: "喵。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "anwhairpin.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "Nakago fox",
			name_cap: "Nakago fox", cn_name_cap: "心月狐",
			variable: "Nakago fox",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume"],
			gender: "n",
			warmth: 10,
			cost: 10000,
			description: "心月幻化人形时偶尔会选择不隐藏狐耳和尾巴，问其原因嘛，大概是因为比较可爱？你说是不是？",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			cursed: 0,
			location: 0,
			iconFile: "Nakago_fox.png",
			accIcon: 0
		},
	
		{
			index: 8,
			name: "neru bunny ears",
			name_cap: "Neru bunny ears", cn_name_cap: "华丽的兔耳",
			variable: "nerubunnyears",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume", "serving"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 3000,
			description: "尼禄兔女郎装的一部分。上手摸会挨骂。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "neru_bunny_ears.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "demon rabbit",
			name_cap: "Demon rabbit", cn_name_cap: "恶魔兔帽子",
			variable: "demon rabbit",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "n",
			warmth: 20,
			cost: 8000,
			description: "邪恶的帽子正在朝着你微笑。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "demon_rabbit.png",
			accIcon: 0
		},
	
		{
			index: 3,
			name: "fashiaaa",
			name_cap: "fashiaaa", cn_name_cap: "丰川祥子发饰",
			variable: "fashiaaa",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "n",
			warmth: 20,
			cost: 8000,
			description: "骄傲绽放的重要之人。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "fashiaaa.png",
			accIcon: 0
		},
	
		{
			index: 49,
			name: "Alice&#39;s dream bow",
			name_cap: "Alice&#39;s dream bow",
			cn_name_cap: "爱丽丝梦境蝴蝶结",
			variable: "Alicesdreambow",
			integrity_max: 100,
			integrity: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 0,
			mask_img: 0,
			mask_img_ponytail: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["school", "formal", "costume", "sticky_fingers", "athletic"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 12000,
			description: "爱丽丝的缎带蝴蝶结，你戴上了这个蝴蝶结，它的经历好像直接作用在了你的身上。这会让使用者变的优雅而活泼。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "Alicesdreambow.png",
			accIcon: 0,
			mainImage: 1,
		},
	
		{
			index: 3,
			name: "liuyinglian",
			name_cap: "liuyinglian", cn_name_cap: "流萤念",
			variable: "liuyinglian",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "n",
			warmth: 20,
			cost: 8000,
			description: "四时花竞巧，九子粽争新。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "liuyinglian.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "disciplinary perdition veil",
			name_cap: "Disciplinary perdition Veil",
			cn_name_cap: "戒律头纱",
			variable: "Aponia veil",
			integrity_max: 200,
			integrity: 200,
			fabric_strength: 100,
			reveal: 500,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 0,
			mask_img: 1,
			mask_img_ponytail: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["holy", "rainproof"],
			gender: "n",
			femininity: 100,
			warmth: 75,
			cost: 10000,
			description: "我必须得到答案，相比起来……生命微不足道。既然世界不能给予我想要的事物，那么我也只能……成为「世界」本身。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "Aponia_veil.png",
			accIcon: 0,
		},
	
		{
			index: 20,
			name: "verosika",
			name_cap: "verosika", cn_name_cap: "维罗茜卡的角",
			variable: "verosika",
			integrity: 900,
			integrity_max: 900,
			fabric_strength: 90,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["dark"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 2000,
			description: "你把她的角掰下来了？",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "verosika jiao.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "benubmaozi",
			name_cap: "Benubmaozi", cn_name_cap: "毛茸茸帽子",
			variable: "benubmaozi",
			integrity: 1000,
			integrity_max: 1000,
			fabric_strength: 50,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "cool", "shade"],
			gender: "f",
			femininity: 200,
			warmth: 50,
			cost: 3500,
			description: "很暖和的毛茸茸帽子，不知道顶着两只什么动物的耳朵。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "benubmaozi.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "Super gamer suit",
			name_cap: "Super gamer suit",
			cn_name_cap: "游戏玩家套装",
			variable: "Supergamersuit",
			integrity_max: 100,
			integrity: 100,
			fabric_strength: 30,
			reveal: 300,
			word: "a",
			one_piece: 0,
			plural: 0,
			hood: 1,
			mask_img: 1,
			mask_img_ponytail: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["rainproof", "athletic"],
			set: "Supergamersuit",
			gender: "f",
			femininity: 100,
			warmth: 1,
			cost: 10000,
			description: "一件十分可爱且精致的衣服，穿上它你就是超高校级的游戏玩家!——来自于《弹丸论破》七海千秋的造型衣服。",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			back_img_colour: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 1,
			outfitSecondary: ["upper", "Super gamer suit"],
		},
	
		{
			index: 691,
			name: "Tendouarisu",
			name_cap: "Tendouarisu",
			cn_name_cap: "爱丽丝的神格证明²",
			variable: "Tendouarisu",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "holy", "athletic"],
			gender: "n",
			warmth: 10,
			cost: 3000,
			description: "爱丽丝的神格证明，变色。",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			cursed: 0,
			location: 0,
			iconFile: "Tendouarisu.png",
			accIcon: 0
		},
	
		{
			index: 1,
			name: "yichika",
			name_cap: "yichika", cn_name_cap: "一花发卡",
			variable: "yichika",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "可爱捏。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "yichika.png",
			accIcon: 0
		},
	
		{
			index: 0,
			name: "lace",
			name_cap: "lace", cn_name_cap: "蕾丝头花",
			variable: "lace",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 900,
			description: "嗅嗅.....有一股淡淡的花香味！捏一捏.....咦......原来是丝网做的花....",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lace.png",
			accIcon: 0
		},
	
		{
			index: 5,
			name: "fgwl",
			name_cap: "Fgwl",
			cn_name_cap: "饭纲丸龙的帽子",
			variable: "fgwl",
			integrity_max: 100,
			integrity: 100,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			one_piece: 0,
			plural: 0,
			hood: 0,
			mask_img: 0,
			mask_img_ponytail: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["formal", "athletic"],
			gender: "f",
			femininity: 100,
			warmth: 1,
			cost: 1000,
			description: "饭纲丸龙的帽子",
			shop: ["clothing", "forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			back_img_colour: 0,
			cursed: 0,
			location: 0,
			iconFile: "fangangwanhat.png",
			accIcon: 0,
			mainImage: 1,
		},
	
		{
			index: 0,
			name: "huaguanlv",
			name_cap: "huaguanlv", cn_name_cap: "花冠",
			variable: "huaguanlv",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 900,
			description: "非常大自然。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "huaguanlv.png",
			accIcon: 0
		},
	
		{
			index: 2,
			name: "dragonbreath veil",
			name_cap: "Dragonbreath veil",
			cn_name_cap: "龙棘",
			variable: "dragonbreath veil",
			integrity_max: 20,
			integrity: 20,
			fabric_strength: 200,
			reveal: 500,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["formal", "event"],
			gender: "n",
			femininity: 100,
			warmth: 75,
			cost: 10000,
			description: "她漫步行过夜的河。",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "longxiaw.png",
			accIcon: 0,
			mainImage: 1,
		},
	
		{
			index: 1,
			name: "gothic bonnet",
			name_cap: "Gothic bonnet", cn_name_cap: "哥特波奈特",
			variable: "gothicbonnet",
			integrity: 80,
			integrity_max: 80,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 0,
			mask_img: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["formal", "costume"],
			gender: "f",
			femininity: 100,
			warmth: 20,
			cost: 700,
			description: "装饰着复杂的黑色缎带与玫瑰的波奈特帽子。",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "gothic_bonnet.png",
			accIcon: "gothic_bonnet_acc.png",
		},
	
		{
			index: 1,
			name: "yaidopin",
			name_cap: "yaidopin", cn_name_cap: "酷酷发卡",
			variable: "yaidopin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "大大加速头发的生长。",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "yaidopin.png",
			accIcon: 0,
		},
	
		{
			index: 64,
			name: "horn of the Loong",
			name_cap: "Horn of the Loong",
			cn_name_cap: "中国龙角",
			variable: "hornoftheLoong",
			integrity_max: 200,
			integrity: 200,
			fabric_strength: 30,
			reveal: 50,
			word: "a",
			one_piece: 0,
			plural: 0,
			hood: 0,
			mask_img: 0,
			mask_img_ponytail: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal", "glasses", "cool", "diving", "serving", "stealthy", "rainproof", "shade", "athletic"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 500,
			description: "中国龙头上会出现的角之一。我是一条小青龙♫小青龙♫ 小青龙♫ 我有许多小秘密♫小秘密 ♫小秘密♫",
			shop: ["clothing", "school", "forest"],
			accessory: 1,
			accessory_colour: 1,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			back_img_colour: 0,
			cursed: 0,
			location: 0,
			iconFile: "horn_of_the_Loong.png",
			accIcon: 0,
			mainImage: 1,
		},
	];

	setup.moddedClothes.head.forEach((x, i) => (x.index = setup.clothes.head.length + i));
	setup.clothes.head.push(...setup.moddedClothes.head);
}
window.initHead = initHead;
